version = 0.1
[default.deploy.parameters]
stack_name = "tulex"
resolve_s3 = true
s3_prefix = "tulex"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
